def fail_with_error(self, message):
    '\n    Prints error message and exits with non-zero exit code\n    '
    print ('Error: ' + message)
    sys.stderr.write(('Error: ' + message))
    sys.exit(1)
