def pre_raise(self):
    if (self.print_cause and (self.cause_traceback != 'None\n')):
        sys.stderr.write(self.cause_traceback)
        sys.stderr.write('\nThe above exception was the cause of the following exception:\n\n')
