{
  final String expectedErrorMessage="This is a test error message!";
  final Exception expectedException=new Exception("test exception");
  EasyMockSupport mockSupport=new EasyMockSupport();
  Logger loggerMock=mockSupport.createMock(Logger.class);
  AtomicInteger testAtomicInteger=new AtomicInteger(0);
  Capture<Exception> exceptionCaptureOne=new Capture<Exception>();
  loggerMock.error(eq(expectedErrorMessage),capture(exceptionCaptureOne));
  expectLastCall().times(1);
  mockSupport.replayAll();
  for (int i=0; i < 5; i++) {
    Utils.logErrorMessageWithThrowableWithCounter(loggerMock,testAtomicInteger,expectedErrorMessage,expectedException,5);
  }
  assertSame("Exception passed to Logger should have been the same instance passed into the Utils method",expectedException,exceptionCaptureOne.getValue());
  mockSupport.verifyAll();
}
